### ISSUE TITLE
Develop a "wire-level" telemetry protocol

### ISSUE THREAD

**Issue by vkottler** [vkottler/senior-design#22]
We intend to use WebSocket to stream data from an arbitrary backend / data source to our UI.

We need to choose a serialized data format to send over this interface. JSON or another ASCII representation is probably simpler than some kind of binary format but work on this protocol should include a basic demo of streaming data to the UI from a program running on another device (any arbitrary language)

The protocol should be particularly good at handling changes in the schema of the data being received on the fly

**Comment by katwalmayank** [comment]
Yeah makes sense. Initially I was thinking JSON, do you think that is still feasible or what?

**Comment by vkottler** [comment]
I think JSON is definitely viable. This work would include coming up with a flexible schedule and to use on top of JSON

**Comment by vkottler** [comment]
I ended up going in a completely different direction for this to support the embedded case (telemetry over radios at 115200 baud). Hoping to have a demo soon

**Comment by vkottler** [comment]
This is now scoped to an entire separate repository
